### ISSUE TITLE
Links Node - Output duplication

### ISSUE THREAD

**Issue by DillonManning** [sixtysecondrevit/RhythmForDynamo#10]
Hi there, I noticed this node's (Links) output jumping around upon each open of the script.  I can fix it by deleting and undoing, but I figured I should point it out. I believe it has to do with the upgrade to 2.0 since it doesn't happen in 1.3.  Hope I'm not jumping the gun on this one.

![rhythm-links switching wires](https://user-images.githubusercontent.com/37595457/39711196-3f147f74-51dc-11e8-9dfc-dd655362ddd3.png)

Dynamo Version : 2.0
Windows 7
Revit 2018.3

**Comment by sixtysecondrevit** [comment]
Thanks for the comment! Definitely because of Dynamo 2.0. Rhythm is not currently 100% compatible with 2.0. I plan on releasing an update pertaining to this in a few months.

**Comment by DillonManning** [comment]
I figured it was a bit early but never hurts to know one of the issues ahead of time. Is this a good place to report any further issues pertaining to the upgrade?

**Comment by sixtysecondrevit** [comment]
Definitely! I appreciate the help in squashing some bugs! Thanks @DillonManning

**Comment by sixtysecondrevit** [comment]
This is fixed in the next release. (Will be out on Friday)
