### ISSUE TITLE
Dimension.ValueString does not return values for the Below field.

### ISSUE THREAD

**Issue by Chrono9084** [sixtysecondrevit/RhythmForDynamo#11]
Pretty much what the title says.  The strings seem to show every dimension field except for the below portion.  See the attached pictures.  I am not sure if this is a limitation or not but it would be amazing if it could get fixed/implemented as I am using this node to grab any overrides in an existing dimension and placing them in a new one.

![image](https://user-images.githubusercontent.com/37596510/41745111-846ed9f4-756b-11e8-8852-48522518dceb.png)
![image](https://user-images.githubusercontent.com/37596510/41745119-8cebd6a4-756b-11e8-8ff3-6c0fe4187462.png)

**Comment by Chrono9084** [comment]
It also looks like you removed the Dimension.MultiSegmentMembers from your latest release.  Is there a different node we can use to get the values from each segment?  It is the node I was using before the Dimension.ValueString node above.

**Comment by sixtysecondrevit** [comment]
I need to revise this node to handle multi seg dims.
![image](https://user-images.githubusercontent.com/15744724/41798976-e8af26f0-762c-11e8-97a7-30df846912e3.png)

**Comment by sixtysecondrevit** [comment]
WIll add to next release. Thanks
