### ISSUE TITLE
Idea . Would be possible to allow system family for Element.Space Node

### ISSUE THREAD

**Issue by mdengusiak** [sixtysecondrevit/RhythmForDynamo#3]
Currently we can see most families that are placed in space but system family like duct and pipes are not picked up and show are null. Would be good to include them if possible

**Comment by sixtysecondrevit** [comment]
Will verify. Considering these are curve based elements. It may take more
work.

**Comment by mdengusiak** [comment]
I guess you could take center of duct, pipe as start point.. to make it easier

**Comment by sixtysecondrevit** [comment]
For sure. Already have a node that does this for cable tray.

**Comment by sixtysecondrevit** [comment]
Better suited for Duct Tape package. WIll consider adding.
