### ISSUE TITLE
Pick Model Elements requests

### ISSUE THREAD

**Issue by cpalexander** [sixtysecondrevit/RhythmForDynamo#4]
It would be great if there were an option in this node to add a maximum number input parameter. For instance, if I only want to be able to select 2 objects at a time, that I could use "2" as another input and it would automatically finish after selected 2 elements.

I'm not sure if that is possible, as it would be nice to not have to hit the "finish" button that appears in the bar, but it would be nice nonetheless.

Thank you.

**Comment by sixtysecondrevit** [comment]
OOh, kind of like this idea. I will look at an option for a node with a numeric input to allow for a selection of a number of items.

**Comment by sixtysecondrevit** [comment]
@cpalexander I finally got around to this and it will be in the next version of Rhythm. _Unfortunately the finish button is not possible in this case._
![20171006-numberedselection](https://user-images.githubusercontent.com/15744724/31280044-4be86146-aa68-11e7-903b-68ee546c449a.gif)
