### ISSUE TITLE
Unable install Rhythm for Dynamo

### ISSUE THREAD

**Issue by b-ardrey23** [sixtysecondrevit/RhythmForDynamo#5]
I am having an issue trying to install rhythm. I installed it is say is installed after I install but I can't find it. When I reopen Dynamo in my installed packages it is no longer there

**Comment by sixtysecondrevit** [comment]
Do you have any restrictions from your IT department on your computer?

**Comment by b-ardrey23** [comment]
I do not

**Comment by sixtysecondrevit** [comment]
Try removing Rhythm from packages directory and reinstalling from package
manager,

**Comment by b-ardrey23** [comment]
I just removed it from the packages directory and reinstalled it is now works thank you.

**Comment by sixtysecondrevit** [comment]
Sounds good, anytime!~
