### ISSUE TITLE
IntegerSlider Versioning

### ISSUE THREAD

**Issue by aaronrumple** [sixtysecondrevit/RhythmForDynamo#6]
The integer slider is hard coded to the 1.2 package (Lines 126, 127). This node fails if you only have 1.3.X installed. The PNG file is installed in the 1.3 path with Dynamo 1.3. Suggest pulling path from current Dynamo version.

      <System.String>\Dynamo\Dynamo Revit\1.2\packages\Rhythm\extra\rhythm-logo-smaller.png</System.String>

      <System.String value="\Dynamo\Dynamo Revit\1.2\packages\Rhythm\extra\rhythm-logo-smaller.png" />

**Comment by sixtysecondrevit** [comment]
Thanks for the feedback! I am actually removing this node from my package as the package Data Shapes has this functionality.

**Comment by sixtysecondrevit** [comment]
Integer slider has been removed from next release
