### ISSUE TITLE
Conflict with standard node Element.SetParameterByNAme

### ISSUE THREAD

**Issue by fhecart** [sixtysecondrevit/RhythmForDynamo#7]
Hello.

i do have some warnings on a dynamo workflow since i use your package.
The standard node Element.SetParameterByName don't work anymore.

Here is the warning (in french) : it finds several definition for recit.elements.element.
Maybe a conflict between your's and the standard? 
"Avertissement:Plusieurs définitions pour 'Revit.Elements.Element' ont été trouvées comme Revit.Elements.Element, Rhythm.Revit.Elements.Element"
i use dynamo 1.32 and revit 2017.
Bye
Florent

**Comment by sixtysecondrevit** [comment]
The standard node does not work at all? Or when you do design script?
