### ISSUE TITLE
Dimension.SetBelowValue for Multi-segment dimensions

### ISSUE THREAD

**Issue by StudioLE** [sixtysecondrevit/RhythmForDynamo#8]
There presently isn't any documentation for how to use the `Dimension.SetBelowValue` node.

[This post from June 2016](https://forum.dynamobim.com/t/override-dimension-values/3566/9) suggests that it is possible but this solution no longer seems to work.

I can get SetBelowValue to work for a single dimension but for multi-segments I feel I've tried every conceivable combination of nodes but nothing to no avail.

For reference the standard dynamo node `Dimension.SetSuffix` will apply unique suffixes to each value when directly passed a dimension and a list of values so one would kind of effect Rhythm to work in the same manner?

**Comment by sixtysecondrevit** [comment]
I am adding this to the next release and it will work with segments.

**Comment by sixtysecondrevit** [comment]
Also, rhythm is heavily documented on Dynamonodes.com and it will be there when updated

**Comment by StudioLE** [comment]
Superb, if you've got it working is there any chance of you pushing a develop branch so I can jump straight in and test it or is it more complex than that?

**Comment by sixtysecondrevit** [comment]
Let me see what I can do. I am actually planning on pushing a new build to the package manager this week,

**Comment by sixtysecondrevit** [comment]
Fixed in version 2018.4.20

**Comment by StudioLE** [comment]
I can confirm this now works as expected, thanks for the great work

**Comment by ParametricMonkey** [comment]
Hi John. Is it possible for this node to work on only ONE segment from a multi-segment dimension?

**Comment by ParametricMonkey** [comment]
Thanks John!
