### ISSUE TITLE
Warning: Application.OpenAndActivateDocumentFile operation failed

### ISSUE THREAD

**Issue by alexberd** [sixtysecondrevit/RhythmForDynamo#9]
The node Application.OpenAndActivateDocumentFile gives the error below:

> Warning: Application.OpenAndActivateDocumentFile operation failed. 
> Switching active documents is not allowed during API event handling.

**Running the following**
Windows 10
Revit 2018
Dynamo Core 1.3.2.2480

**Comment by sixtysecondrevit** [comment]
Yes, this node does not work. It was an experiment and somehow got bundled in. You are not able to activate a document through Dynamo. Use "Application.OpenDocumentFile" instead.
